/**
 * Constantes del sistema - Optimizado
 */

// Constantes inmutables (performance + seguridad)
const TERCERO_DEFAULTS = Object.freeze({
  // Flags principales
  CLIENTE: 'S', VENDED: 'N', PROVEED: 'N',
  // Configuración
  VRULTCOM: '0', ETERRITORIAL: 'NI', RESPONSABILIDADES: 'R-99-PN', CLASIFICAID: 1,
  // Flags sistema
  FACTELECT: 'N', NOREPORCIR: 'N', SINCRONIZADO: 'N', PORRETEN: 'N',
  // Roles específicos
  CONDUCTOR: 'N', TOMADOR: 'N', PROPIETARIO: 'N', EMPLEADO: 'N', FIADOR: 'N', OTRO: 'N',
  // Operaciones
  MESA: 'N', MOSTRADOR: 'N',
  // Valores numéricos
  MAXCREDCXC: 0, MAXCREDDIAS: 0, ZONA1: 1
});

const PAGINATION = Object.freeze({ DEFAULT_PAGE: 1, DEFAULT_LIMIT: 50, MAX_LIMIT: 500, MIN_PAGE: 1, MIN_LIMIT: 1 });
const ERROR_CODES = Object.freeze({
  BAD_REQUEST: 'BAD_REQUEST', NOT_FOUND: 'NOT_FOUND', CONFLICT: 'CONFLICT', 
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR', CIUDANE_INEXISTENTE: 'CIUDANE_INEXISTENTE',
  ZONA_INEXISTENTE: 'ZONA_INEXISTENTE', LISTA_PRECIO_INEXISTENTE: 'LISTA_PRECIO_INEXISTENTE',
  NIT_DUPLICADO: 'NIT_DUPLICADO', FK_VIOLATION: 'FK_VIOLATION'
});

const TIPOS_DOCUMENTO = Object.freeze({ CEDULA: 'C', NIT: 'NIT', PASAPORTE: 'PA', CEDULA_EXTRANJERIA: 'CE' });
const NATURALEZA_JURIDICA = Object.freeze({ NATURAL: 'N', JURIDICA: 'J' });
const FIELD_LIMITS = Object.freeze({
  NIT: 20, NOMBRE: 80, DIRECC1: 60, DIRECC2: 60, CIUDAD: 30,
  TELEF1: 15, TELEF2: 15, EMAIL: 100, CODIGO: 8, DESCRIP: 40
});

module.exports = {
  TERCERO_DEFAULTS, PAGINATION, ERROR_CODES, 
  TIPOS_DOCUMENTO, NATURALEZA_JURIDICA, FIELD_LIMITS
};
